apiVersion: v1
kind: Pod
metadata:
  name: envvar-demo
  labels: 
    purpose: demonstrate-envvars
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:  
      - configMapRef:
          name: pod-config
      
    