apiVersion: app/v1 
kind: Deployment 
metadata: 
  - name: nginx 
    # These are deployment labels
    labels: 
      purpose: deployment-demo 
      project: roboshop 
      app: nginx
spec: 
 replicaset: 2 
 # These are the labels replica set uses to create pod replicas,this should match pod labels
 selector: 
   matchLabels: 
      purpose: deployment-demo 
      project: roboshop 
      app: nginx
 # This is Pod definition     
 template: 
   metadata: 
     labels: 
        purpose: deployment-demo 
        project: roboshop 
        app: nginx
   spec: 
     containers:
       - name: nginx
         image: nginx:stable-perl
             
      
             